# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'New'), (10, 'List build in progress'), (20, 'List complete')], default=1)),
                ('contacts', models.ManyToManyField(blank=True, to='contacts.Contact')),
            ],
        ),
    ]
