# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180801_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (10, 'In Progress (building list)'), (20, 'Complete (ready to use)')], default=1),
        ),
    ]
