# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180802_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOptOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('opt_out_type', models.IntegerField(choices=[(1, 'Calling')], db_index=True, default=1)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='phoneoptout',
            unique_together=set([('opt_out_type', 'phone_number')]),
        ),
    ]
