# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20181018_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneoptout',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
