# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_phoneoptout_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneoptout',
            name='source',
            field=models.CharField(default='Legacy backfill', max_length=255),
            preserve_default=False,
        ),
    ]
