# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-20 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('event_external_id', models.CharField(db_index=True, max_length=128)),
                ('max_recipients', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=2048)),
                ('sender_display_name', models.CharField(max_length=128, null=True)),
                ('sender_email', models.EmailField(max_length=254, null=True)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Sent'), (4, 'Skipped')], default=1)),
                ('subject', models.CharField(max_length=128)),
                ('submitted', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_external_id', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EventPromotionRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_external_id', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventpromotion',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='events.EventPromotionRecipient'),
        ),
    ]
