# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-20 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpromotionrecipient',
            name='user_external_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='eventpromotionrequest',
            name='event_external_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='eventpromotionrequest',
            name='user_external_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
