# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpromotion',
            name='subject',
            field=models.CharField(default=b'Please come to our Volunteer event', max_length=128),
        ),
    ]
