# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180622_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpromotion',
            options={'ordering': ['-date_submitted']},
        ),
    ]
