# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180626_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPromotionRecipient',
        ),
        migrations.AlterField(
            model_name='eventpromotion',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='contacts.Contact'),
        ),
    ]
