# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180730_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpromotion',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (10, 'Approved'), (20, 'In Progress'), (30, 'Sent'), (40, 'Skipped')], default=1),
        ),
    ]
