# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-18 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180911_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpromotion',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (10, 'Approved'), (20, 'In Progress'), (30, 'Sent'), (40, 'Skipped'), (50, 'Event Not Approved'), (60, 'Expired')], default=1),
        ),
    ]
