# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-30 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180918_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpromotion',
            name='sent_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
