#!/bin/bash


# this bit isn't dialed in, tbqh.
pip install virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
mkvirtualenv ourrevolution

echo "Installing requirements from requirements.txt ..."
pip install -r requirements.txt

echo "Creating Postgres user & database..."
createuser ourrevolution && createdb -Oourrevolution -Eutf8 ourrevolution

echo "Filling out .env file..."
echo "DATABASE_URL=postgres://ourrevolution@localhost:5432/ourrevolution" >> .env
# only use if needed
# echo "DATABASE_URL=postgres:///ourrevolution" >> .env
echo "DEBUG=1" >> .env
key=`date | md5` && echo "SECRET_KEY=$key" >> .env
# only use if needed
# echo "SECRET_KEY=lebowski" >> .env
# echo "AUTH0_DOMAIN=lebowski" >> .env
# echo "AUTH0_CLIENT_ID=lebowski" >> .env
# echo "AUTH0_CLIENT_SECRET=lebowski" >> .env
# echo "AUTH0_CALLBACK_URL=lebowski" >> .env
# echo "AUTH0_CANDIDATE_CALLBACK_URL=lebowski" >> .env

echo "Migrating database..."
./manage.py migrate

echo "Creating an admin user for you..."
./manage.py createsuperuser
