# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-04 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizing_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizingHubLoginAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', wagtail.wagtailcore.fields.RichTextField()),
                ('show', models.BooleanField(default=False, help_text='Show alert on organizing hub login page.')),
            ],
        ),
    ]
