# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizing_hub', '0002_organizinghubloginalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizinghubloginalert',
            name='alert_level',
            field=models.IntegerField(choices=[(1, b'success'), (2, b'info'), (3, b'warning'), (4, b'danger')], default=3, help_text='\n        Set the alert style corresponding to Bootstrap 3 alert levels.\n\n        See: https://getbootstrap.com/docs/3.3/components/#alerts-dismissible\n        '),
        ),
    ]
