# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-03 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizing_hub', '0003_organizinghubloginalert_alert_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizinghubloginalert',
            name='alert_level',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Info'), (3, 'Warning'), (4, 'Danger')], default=3, help_text='\n        Set the alert style corresponding to Bootstrap 3 alert levels.\n\n        See: https://getbootstrap.com/docs/3.3/components/#alerts-dismissible\n        '),
        ),
    ]
