# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0070_auto_20180806_2138'),
        ('organizing_hub', '0006_auto_20181004_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizingHubAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('local_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='local_groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizingHubFeatureAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.IntegerField(choices=[(1, 'Calls'), (2, 'test 2'), (3, 'test 3'), (4, 'test 4')])),
                ('organizing_hub_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizing_hub.OrganizingHubAccess')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='organizinghubfeatureaccess',
            unique_together=set([('feature', 'organizing_hub_access')]),
        ),
    ]
