# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizing_hub', '0007_auto_20181016_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizinghubfeatureaccess',
            name='feature',
            field=models.IntegerField(choices=[(1, 'Calling Tool')]),
        ),
    ]
