# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizing_hub', '0010_auto_20181023_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizinghubdashboardpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('link_block', wagtail.wagtailcore.blocks.StructBlock([('text', wagtail.wagtailcore.blocks.TextBlock()), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('feature_access_required', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(1, 'Call Tool'), (2, 'Nominations: Priority Support')], help_text='\n                Select Feature if access should be restricted only to local\n                groups that have this Feature enabled.\n                ', required=False))]))]),
        ),
        migrations.AlterField(
            model_name='organizinghubfeatureaccess',
            name='feature',
            field=models.IntegerField(choices=[(1, 'Call Tool'), (2, 'Nominations: Priority Support')]),
        ),
    ]
