# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 03:50
from __future__ import unicode_literals

import calls.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local_groups', '0070_auto_20180806_2138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0004_auto_20180802_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_distance', models.IntegerField()),
                ('max_recipients', models.IntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('postal_code', models.CharField(max_length=12)),
                ('script', models.TextField(max_length=2000)),
                ('status', models.IntegerField(choices=[(1, 'New'), (10, 'Approved'), (20, 'In Progress'), (30, 'Paused'), (40, 'Complete'), (50, 'Declined'), (60, 'Suspended')], default=calls.models.CallCampaignStatus((1, 'New')))),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CallProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='callcampaign',
            name='callers',
            field=models.ManyToManyField(blank=True, related_name='campaigns_as_caller', to='calls.CallProfile'),
        ),
        migrations.AddField(
            model_name='callcampaign',
            name='contact_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactList'),
        ),
        migrations.AddField(
            model_name='callcampaign',
            name='local_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_groups.Group'),
        ),
        migrations.AddField(
            model_name='callcampaign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_as_owner', to='calls.CallProfile'),
        ),
        migrations.AddField(
            model_name='call',
            name='call_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.CallCampaign'),
        ),
        migrations.AddField(
            model_name='call',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.CallProfile'),
        ),
        migrations.AddField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
    ]
