# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('question', models.IntegerField(choices=[(1, 'Opt out of future calls?')])),
                ('answer', models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Maybe')])),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.Call')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='callresponse',
            unique_together=set([('call', 'question')]),
        ),
    ]
