# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20180808_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callresponse',
            name='answer',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Maybe'), (4, 'No answer'), (5, 'Wrong number'), (6, 'Busy'), (7, 'Not Home'), (8, 'Do not call')]),
        ),
        migrations.AlterField(
            model_name='callresponse',
            name='question',
            field=models.IntegerField(choices=[(1, 'Did you talk to the contact?'), (2, 'Why not?'), (3, 'Does the contact want to take action with your group?'), (4, 'Did you leave a voicemail?'), (5, 'Did you send a text message?')]),
        ),
    ]
