# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180802_0039'),
        ('calls', '0004_auto_20180808_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcampaign',
            name='contact_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactList'),
        ),
        migrations.AlterUniqueTogether(
            name='call',
            unique_together=set([('call_campaign', 'contact')]),
        ),
    ]
