# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-29 02:07
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_auto_20180907_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcampaign',
            name='state_or_territory',
            field=localflavor.us.models.USStateField(default='CA', max_length=2),
        ),
    ]
