# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0016_auto_20181015_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
