# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0017_auto_20181015_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcampaign',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (10, 'Approved'), (20, 'In Progress'), (30, 'Paused'), (40, 'Complete'), (50, 'Declined'), (60, 'Suspended')], default=1, help_text='\n        Contact List is required to be complete and non-empty for certain\n        Campaign statuses.\n        '),
        ),
    ]
