# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64, null=True, verbose_name='Group Name')),
                ('group_id', models.CharField(max_length=4, null=True)),
                ('group_nomination_process', models.TextField(max_length=500, null=True, verbose_name='Group Nomination Process')),
                ('rep_email', models.EmailField(max_length=254, null=True, verbose_name='Contact Email')),
                ('rep_first_name', models.CharField(max_length=35, null=True, verbose_name='First Name')),
                ('rep_last_name', models.CharField(max_length=35, null=True, verbose_name='Last Name')),
                ('rep_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Phone Number')),
                ('candidate_email', models.EmailField(max_length=255, null=True, verbose_name='Candidate Email')),
                ('candidate_first_name', models.CharField(max_length=255, null=True, verbose_name='Candidate First Name')),
                ('candidate_last_name', models.CharField(max_length=255, null=True, verbose_name='Candidate Last Name')),
                ('candidate_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Candidate Phone Number')),
                ('candidate_office', models.CharField(max_length=255, null=True, verbose_name='Candidate Office')),
                ('candidate_state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('candidate_website_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate Website URL')),
                ('candidate_facebook_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate Facebook URL')),
                ('candidate_twitter_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate Twitter URL')),
                ('candidate_instagram_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate Instagram URL')),
                ('candidate_youtube_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate YouTube URL')),
                ('candidate_progressive_champion', models.TextField(max_length=500, null=True, verbose_name='How is the candidate a progressive champion?')),
                ('candidate_community', models.TextField(max_length=500, null=True, verbose_name='What has the candidate done for the community?')),
                ('candidate_presidential_support', models.BooleanField(default=False, verbose_name='Did the candidate publicly support anyone in the Primaries or/and General Elections for President in 2016?')),
                ('candidate_presidential_support_who', models.TextField(blank=True, max_length=128, null=True, verbose_name='If yes, who?')),
                ('candidate_platform', models.TextField(max_length=500, null=True, verbose_name="Briefly describe the candidate's platform?")),
                ('candidate_goals', models.TextField(max_length=500, null=True, verbose_name="What are some of the candidate's top goals?")),
                ('candidate_plan', models.TextField(max_length=500, null=True, verbose_name='What does the candidate plan to accomplish while in office?')),
                ('candidate_group_organizing', models.BooleanField(default=False, verbose_name='Are people in the nominating Our Revolution group willing to organize for the candidate?')),
                ('candidate_group_organizing_actions', models.TextField(max_length=500, null=True, verbose_name='What actions will the group take and how many people have agreed to volunteer/work?')),
                ('candidiate_importance_of_endorsement', models.TextField(max_length=500, null=True, verbose_name='Why is an our Revolution national endorsement important in this race?')),
            ],
        ),
    ]
