# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='group_id',
            field=models.CharField(max_length=4, null=True, verbose_name='Group ID'),
        ),
    ]
