# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 20:53
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='candidate_state',
            field=localflavor.us.models.USStateField(max_length=2, null=True, verbose_name='Candidate State'),
        ),
    ]
