# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-15 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0002_auto_20170608_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='nomination',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='nominations.Nomination'),
        ),
    ]
