# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-05 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0002_auto_20170525_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_first_name', models.CharField(max_length=255, null=True, verbose_name='Candidate First Name')),
                ('candidate_last_name', models.CharField(max_length=255, null=True, verbose_name='Candidate Last Name')),
                ('candidate_email', models.EmailField(max_length=255, null=True, verbose_name='Candidate Email')),
                ('candidate_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Candidate Phone Number')),
                ('candidate_office', models.CharField(max_length=255, null=True, verbose_name='Candidate Office')),
                ('candidate_state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('candidate_website_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate Website URL')),
                ('candidate_facebook_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate Facebook URL')),
                ('candidate_twitter_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate Twitter URL')),
                ('candidate_instagram_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate Instagram URL')),
                ('candidate_youtube_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate YouTube URL')),
                ('question_wealthy_fair_share', models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, verbose_name='Today, we live in the richest country in the history of the world, but that reality means little because much of that wealth is controlled by a tiny handful of individuals. To address that, the wealthy and large corporations must pay their fair share in taxes.')),
                ('position_wealthy_fair_share', models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:")),
            ],
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='candidate_email',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='candidate_facebook_url',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='candidate_instagram_url',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='candidate_office',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='candidate_phone',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='candidate_state',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='candidate_twitter_url',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='candidate_website_url',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='candidate_youtube_url',
        ),
    ]
