# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-06 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0002_auto_20170606_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='nomination',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nominations.Nomination'),
        ),
        migrations.AlterField(
            model_name='application',
            name='questionnaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nominations.Questionnaire'),
        ),
    ]
