# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-06 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0003_auto_20170606_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('removed', 'Denied')], default='incomplete', max_length=16),
        ),
    ]
