# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0003_auto_20170615_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=16),
        ),
    ]
