# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-05 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0003_auto_20170605_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='platform_citizens_united',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_climate_change',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_college',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_defense_spending',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_deportation_machine',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_healthcare',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_infrastructure',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_lgbt',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_native_rights',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_palestine_israel',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_pay_equity',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_peace',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_racial_justice',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_reproductive_rights',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_right_to_vote',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_social_security',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_trade_deals',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_undocumented_immigration',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_veterans',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_youth_jobs',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='position_minimum_wage',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='position_too_big_to_fail',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_citizens_united',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_climate_change',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_college',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_defense_spending',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_deportation_machine',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_healthcare',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_infrastructure',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_lgbt',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_local_issues',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_minimum_wage',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_native_rights',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_palestine_israel',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_pay_equity',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_peace',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_racial_justice',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_reproductive_rights',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_right_to_vote',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_social_security',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_too_big_to_fail',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_trade_deals',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_undocumented_immigration',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_veterans',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_youth_jobs',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_wealthy_fair_share',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='Today, we live in the richest country in the history of the world, but that reality means little because much of that wealth is controlled by a tiny handful of individuals. To address that, the wealthy and large corporations must pay their fair share in taxes.'),
        ),
    ]
