# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-05 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0004_auto_20170605_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='candidate_state',
            field=localflavor.us.models.USStateField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_citizens_united',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='Citizens United, a 5-4 Supreme Court decision, resulted in enabling the wealthiest people and largest corporations in this country to contribute unlimited amounts of money to campaigns. This decision must be overturned and corruption in politics must end. This means fighting to pass a constitutional amendment making it clear that Congress and the states have the power to regulate money in elections. We must also eliminate super PACs and other outside spending abuses and work to aggressively enforce campaign finance rules.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_climate_change',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='The United States must lead the world in tackling climate change, if we are to make certain that this planet is habitable for our children and grandchildren. We must transform our energy system away from polluting fossil fuels, and towards energy efficiency and sustainability.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_college',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='Every American who studies hard in school should be able to go to college regardless of how much money their parents make and without going deeply into debt. For that, we need to work towards making tuition free at public colleges and universities throughout America, stopping the federal government from making a profit on student loans.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_defense_spending',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='The U.S. defense spending is larger than that of the next seven largest defense budgets. We must firmly reject any increase to defense spending at the cost of cuts to domestic social spending.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_deportation_machine',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='The inhumane deportation machine must be dismantled by ending deportation programs, closing down private detention centers, offering humane treatment and asylum to victims of violence and minors fleeing from dangerous circumstances.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_healthcare',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='Healthcare is a human right. Our healthcare system needs to work for all of us. We must guarantee healthcare as a right of citizenship by enacting a Medicare for all single-payer healthcare system, as well as lowering the price for prescription drugs.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_infrastructure',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name="The U.S.'s infrastructure, from our roads and bridges, to our dams, waterways and electrical grid, have not been properly invested in nor used the advances in technology for maintenance or improvements. America is long overdue to rebuild our crumbling roads, bridges, railways, airports, public transit systems, ports, dams, wastewater plants, and other infrastructure needs."),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_lgbt',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='The United States has made remarkable progress on gay rights in a relatively short amount of time. But there is still much work to be done. In many states, it is still legal to fire someone for being gay. It is legal to deny someone housing for being transgender. That is unacceptable and must change. We must end discrimination in all forms.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_local_issues',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='Briefly list important local issues included in your platform.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_minimum_wage',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='No one who works 40-hours a week should live in poverty. The minimum wage needs to be a livable wage of $15 an hour.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_native_rights',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='The United States must not just honor Native American treaty rights and tribal sovereignty, it must also move away from a relationship of paternalism and control, and toward one of deference and support. That means supporting tribal sovereignty and tribal jurisdiction, honoring the treaties and federal statutes, improving housing and education, as well as by protecting sacred places and Native American cultures.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_palestine_israel',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='The U.S. must have a just approach to the Palestinian and Israeli conflict; one that supports Israels right to exist and that denounces human rights abuses and crimes against humanity committed by the state of Israel against the Palestinian people.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_pay_equity',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='Do everything possible to ensure pay equity for women.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_peace',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='The U.S. must move away from a policy of unilateral military action, and toward a policy of emphasizing compassion, diplomacy, and ensuring the decision to go to war is a last resort.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_racial_justice',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='African-Americans and Latinos are twice as likely to be arrested and almost four times as likely to experience the use of force during encounters with the police. They also comprise well over half of all prisoners, even though African-Americans and Latinos make up approximately one quarter of the total US population. We must change this by de-militarizing our police forces, ban for-profit prisons, turn back from the War on Drugs, eliminate mandatory minimums, and increase investment in programs that help individuals recover from substance abuse and mental health problems.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_reproductive_rights',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='Expand and protect the reproductive rights of women'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_right_to_vote',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='In order to protect our democracy, we must fight for a publicly financed, transparent system of campaign financing that amplifies small donations. We must also ensure that all Americans are guaranteed an effective right to vote.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_social_security',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='Social Security must be expanded so that every American can retire with dignity.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_too_big_to_fail',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='Huge financial institutions must be broken up so they are no longer too big to fail.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_trade_deals',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name="Trade deals like TPP, NAFTA, CAFTA, and PNTR have cost the U.S. thousands of jobs, allowed corporations to shut down operations in the US and move work to low-wage countries where people are forced to work for pennies an hour. We must do everything we can to reverse these effects from current trade deals and ensure we don't sign on to anymore that place corporate profits ahead of working class and poor people in the U.S. and throughout the world."),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_undocumented_immigration',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='Despite the central role immigrants play in our economy and in our daily lives, undocumented workers are reviled by some for political gain and shunted into the shadows. It is time for this disgraceful situation to end. We must pave the way for a swift legislative path to citizenship for 11 million undocumented immigrants and protect programs like DACA.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_veterans',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='As a nation, we have a moral obligation to provide the best quality care to those who have put their lives on the line to defend us. Taking care of our veterans is a cost of war. The Department of Veterans Affairs must be fully funding and expanded so that every veteran gets the care that they have earned and deserve. Additionally, claim processing, mental health and dental services, and access to the VA must be improved.'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question_youth_jobs',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1, null=True, verbose_name='It is critically important to create jobs for disadvantaged young Americans by investing in a youth jobs programs.'),
        ),
    ]
