# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0004_nomination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=16),
        ),
    ]
