# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0006_auto_20170616_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=16),
        ),
    ]
