# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-17 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0007_questionnaire_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='position',
            field=models.TextField(max_length=500, null=True, verbose_name="Candidate's position on this issue:"),
        ),
    ]
