# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-17 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0008_auto_20170617_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
