# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0011_auto_20170619_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(choices=[('a', 'Agree'), ('b', 'Disagree'), ('c', 'Mostly agree'), ('d', 'Mostly disagree')], max_length=1),
        ),
    ]
