# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-19 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0012_auto_20170619_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationresponse',
            name='response',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='response',
            name='position',
            field=models.TextField(max_length=1000, null=True, verbose_name="Candidate's position on this issue:"),
        ),
    ]
