# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-20 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0014_questionnaire_candidate_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Candidate City'),
        ),
    ]
