# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-21 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0015_application_candidate_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='candidate_volunteer_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Candidate Volunteer URL'),
        ),
    ]
