# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-21 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0017_auto_20170621_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
