# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-22 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0017_auto_20170621_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='authorized_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Authorized Email'),
        ),
    ]
