# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-27 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0018_application_authorized_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('sent', 'Sent')], default='incomplete', max_length=16),
        ),
    ]
