# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0020_auto_20170628_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='general_election_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='General Election Date'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='primary_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primary Election Date'),
        ),
    ]
