# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0022_auto_20170707_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='general_election_date',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='primary_date',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='general_election_date',
            field=models.DateField(blank=True, null=True, verbose_name='General Election Date'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='primary_election_date',
            field=models.DateField(blank=True, null=True, verbose_name='Primary Election Date'),
        ),
    ]
