# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-07 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0023_auto_20170707_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='candidate_bio',
            field=models.TextField(default='', max_length=500, verbose_name='Candidate Bio'),
            preserve_default=False,
        ),
    ]
