# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-07 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0025_auto_20170707_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='candidate_held_office',
            field=models.NullBooleanField(default=False, verbose_name='Has the candidate ever held public office?'),
        ),
    ]
