# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0028_auto_20170707_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='vol_incumbent',
            field=models.NullBooleanField(verbose_name='Incumbent?'),
        ),
    ]
