# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0030_auto_20170713_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='general_election_date',
            field=models.DateField(null=True, verbose_name='General Election Date'),
        ),
    ]
