# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-24 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0033_auto_20170724_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='submitted_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted at'),
        ),
    ]
