# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0034_auto_20170724_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('initiative', 'Initiative')], default='candidate', max_length=16),
        ),
    ]
