# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0035_application_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='type',
        ),
    ]
