# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0050_merge_20170619_2007'),
        ('nominations', '0038_auto_20170804_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('submitted_dt', models.DateTimeField(blank=True, null=True, verbose_name='Submitted at')),
                ('name', models.CharField(max_length=254)),
                ('rep_email', models.EmailField(max_length=254, null=True, verbose_name='Contact Email')),
                ('rep_first_name', models.CharField(max_length=35, null=True, verbose_name='First Name')),
                ('rep_last_name', models.CharField(max_length=35, null=True, verbose_name='Last Name')),
                ('rep_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('removed', 'Denied')], default='incomplete', max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_groups.Group', to_field='group_id')),
            ],
        ),
    ]
