# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0041_auto_20170804_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeapplication',
            name='additional_info',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Any additional information you want to share?'),
        ),
        migrations.AddField(
            model_name='initiativeapplication',
            name='county',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='initiativeapplication',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='What would the initiative do?'),
        ),
        migrations.AddField(
            model_name='initiativeapplication',
            name='question',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='How will the question appear on the ballot?'),
        ),
        migrations.AddField(
            model_name='initiativeapplication',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='initiativeapplication',
            name='vote',
            field=models.NullBooleanField(verbose_name='How to vote:'),
        ),
        migrations.AlterField(
            model_name='initiativeapplication',
            name='name',
            field=models.CharField(max_length=254, null=True, verbose_name=' Initiative Name'),
        ),
    ]
