# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0042_auto_20170804_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted')], default='submitted', max_length=16),
        ),
    ]
