# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0045_auto_20170804_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiativeapplication',
            options={'verbose_name': 'Ballot Initiative Application'},
        ),
    ]
