# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0046_auto_20170804_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeapplication',
            name='locality',
            field=models.CharField(choices=[('city', 'Citywide'), ('county', 'Countywide'), ('state', 'Statewide')], default='state', max_length=16),
        ),
    ]
