# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0049_auto_20170804_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeapplication',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('needs-research', 'Needs Research'), ('needs-staff-review', 'Needs Staff Review'), ('approved', 'Endorsed'), ('removed', 'Not Endorsed')], default='submitted', max_length=64),
        ),
    ]
