# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-09 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0050_auto_20170804_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='completed_by_candidate',
            field=models.NullBooleanField(),
        ),
    ]
