# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-10 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0051_questionnaire_completed_by_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='vol_type_of_race',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of Race:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vol_dem_challenger',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='If primary, who are the Democratic challengers?'),
        ),
    ]
