# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-10 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0052_auto_20170810_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='vol_incumbent',
            new_name='vol_has_incumbent',
        ),
    ]
