# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-10 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0053_auto_20170810_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='vol_general_challengers',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='If general election, who are the other candidates running and party affiliation if applicable?'),
        ),
        migrations.AddField(
            model_name='application',
            name='vol_incumbent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='If incumbent, who?'),
        ),
        migrations.AddField(
            model_name='application',
            name='vol_primary_challengers',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='If there is a primary, who are the other candidates running and party affiliation if applicable or relevant?'),
        ),
    ]
