# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0053_auto_20170907_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='vol_notes',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notes:'),
        ),
    ]
