# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-10 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0054_auto_20170810_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='vol_dem_challenger',
        ),
        migrations.AlterField(
            model_name='application',
            name='vol_has_incumbent',
            field=models.NullBooleanField(verbose_name='Is there an incumbent?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vol_incumbent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='If there is an incumbent, who is it, and what party?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vol_type_of_race',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of race:'),
        ),
    ]
