# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-02 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0055_auto_20170928_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='classification_level',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III')], default='1', max_length=64),
        ),
        migrations.AddField(
            model_name='application',
            name='local_group_info',
            field=models.TextField(blank=True, null=True, verbose_name='OR Local Group Info:'),
        ),
        migrations.AddField(
            model_name='application',
            name='local_support',
            field=models.TextField(blank=True, null=True, verbose_name='Notes or Flags:'),
        ),
        migrations.AddField(
            model_name='application',
            name='staff',
            field=models.CharField(choices=[('1', 'Erika Andiola')], default='1', max_length=64),
        ),
        migrations.AddField(
            model_name='application',
            name='staff_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes or Flags:'),
        ),
        migrations.AddField(
            model_name='application',
            name='state_of_the_race',
            field=models.TextField(blank=True, null=True, verbose_name='State of the Race:'),
        ),
        migrations.AddField(
            model_name='application',
            name='vet',
            field=models.TextField(blank=True, null=True, verbose_name='Vet:'),
        ),
        migrations.AddField(
            model_name='application',
            name='vet_status',
            field=models.CharField(choices=[('1', 'Passed'), ('2', 'Failed')], default='1', max_length=64),
        ),
    ]
