# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-02 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0056_auto_20171002_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='nomination',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='nominations.Nomination', verbose_name='Group Nomination Form:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vet_status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Passed'), ('2', 'Failed')], default='0', max_length=64),
        ),
    ]
