# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-02 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0057_auto_20171002_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='staff_bio',
            field=models.TextField(blank=True, null=True, verbose_name='Candidate Bio:'),
        ),
    ]
