# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-02 01:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0058_application_staff_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='local_group_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='OR Local Group Info:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='local_support',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Local Support:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='staff_bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Candidate Bio:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='staff_notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notes or Flags:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='state_of_the_race',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='State of the Race:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vet',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vet:'),
        ),
    ]
