# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-02 02:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0060_auto_20171002_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='local_group_info',
            field=ckeditor.fields.RichTextField(blank=True, help_text="This will prepopulate from the local group's endorsement process if left blank.", null=True, verbose_name='OR Local Group Info:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='local_support',
            field=ckeditor.fields.RichTextField(blank=True, help_text="This will prepopulate from the local group's support question if left blank.", null=True, verbose_name='Local Support:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='staff_bio',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This will prepopulate from the candidate questionnaire if left blank.', null=True, verbose_name='Candidate Bio:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='staff_notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This will prepopulate from volunteer notes if left blank.', null=True, verbose_name='Notes or Flags:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vet',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vet Details:'),
        ),
    ]
