# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0063_application_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='vol_other_progressives',
            field=models.TextField(blank=True, help_text='Please indicate party affiliation and other progressives. Max length 500 characters.', max_length=500, null=True, verbose_name='Other candidates running:'),
        ),
    ]
