# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-12 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0064_auto_20171010_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='vet_status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Passed'), ('2', 'Failed'), ('3', 'Not Submitted')], default='0', max_length=64),
        ),
    ]
