# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-12 17:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0065_auto_20171212_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='staff_notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This will prepopulate from volunteer notes if left blank.', null=True, verbose_name='Staff Notes or Flags:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vol_notes',
            field=models.TextField(blank=True, help_text='Max length 1000 characters.', max_length=1000, null=True, verbose_name='Volunteer Notes:'),
        ),
    ]
