# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-08 00:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0067_application_staff_20171218_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominationsPlatformAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('show', models.BooleanField(default=False, help_text='Show alert on nominations platform pages.')),
            ],
        ),
    ]
