# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-08 00:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0068_nominationsplatformalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationsplatformalert',
            name='content',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
