# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0069_auto_20180208_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('party', models.CharField(blank=True, max_length=255, null=True, verbose_name='Candidate Party Affiliation')),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominations.Application')),
            ],
        ),
    ]
