# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-23 00:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0069_auto_20180208_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stand_out_information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
