# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-15 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0070_auto_20180215_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('needs-group-form-and-questionnaire', 'Needs Group Form and Questionnaire'), ('needs-questionnaire', 'Group Form Complete, Needs Questionnaire'), ('needs-group-form', 'Needs Group Form, Questionnaire Complete'), ('incomplete', 'Needs Submission'), ('submitted', 'Submitted'), ('needs-research', 'Needs Research'), ('needs-staff-review', 'Needs Staff Review'), ('unde-review', 'Under Review'), ('approved', 'Endorsed'), ('removed', 'Not Endorsed'), ('expired', 'Expired'), ('hold', 'Hold')], default='needs-group-form-and-questionnaire', max_length=64),
        ),
    ]
