# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-28 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0070_auto_20180220_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='questionnaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nominations.Questionnaire'),
        ),
    ]
