# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-26 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0070_application_stand_out_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('party', models.IntegerField(blank=True, choices=[(1, 'Democratic'), (2, 'Green'), (3, 'Independent/No Party Affiliation'), (4, 'Republican'), (5, 'Libertarian'), (6, 'Vermont Progressive'), (99, 'Other')], null=True)),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominations.Application')),
            ],
        ),
    ]
