# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-27 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0071_applicationcandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcandidate',
            name='party',
            field=models.IntegerField(blank=True, choices=[(1, 'Democratic Party'), (2, 'Green Party'), (3, 'Independent/No Party Affiliation'), (4, 'Republican Party'), (5, 'Libertarian Party'), (6, 'Vermont Progressive Party'), (99, 'Other')], null=True),
        ),
    ]
