# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-28 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0070_auto_20180220_1611'),
        ('nominations', '0073_application_primary_election_type'),
    ]

    operations = [
    ]
