# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-01 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0075_auto_20180228_2104'),
        ('nominations', '0074_merge_20180228_2357'),
    ]

    operations = [
    ]
