# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-02 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0076_merge_20180301_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('bulk_change_application_status', 'Can bulk change status of applications'),), 'verbose_name': 'Candidate Application'},
        ),
    ]
