# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-12 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0077_auto_20180302_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('bulk_change_application_status', 'Can bulk change status of applications'), ('export_pdf_application', 'Can export to pdf')), 'verbose_name': 'Candidate Application'},
        ),
    ]
