# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-03 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nominations', '0079_application_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeapplication',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
