# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-02 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0083_nominationsplatformalert_alert_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationsplatformalert',
            name='alert_level',
            field=models.IntegerField(choices=[(1, 'success'), (2, 'info'), (3, 'warning'), (4, 'danger')], default=3, help_text='\n        Set the alert style corresponding to Bootstrap 3 alert levels.\n\n        See: https://getbootstrap.com/docs/3.3/components/#alerts-dismissible\n        '),
        ),
    ]
