# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-03 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0085_auto_20181003_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationsplatformalert',
            name='alert_level',
            field=models.CharField(choices=[('danger', 'Danger (Red)'), ('info', 'Info (Blue)'), ('success', 'Success (Green)'), ('warning', 'Warning (Yellow)')], default='warning', help_text='\n        Set the alert style corresponding to Bootstrap 3 alert levels.\n\n        See: https://getbootstrap.com/docs/3.3/components/#alerts-dismissible\n        ', max_length=16),
        ),
    ]
