# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-14 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0087_auto_20181004_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='candidate_is_member',
            field=models.NullBooleanField(verbose_name='Is the candidate a member of Our Revolution?'),
        ),
    ]
