# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-14 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0088_questionnaire_candidate_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='candidate_is_member',
            field=models.NullBooleanField(verbose_name='Is candidate a member of Our Revolution?'),
        ),
    ]
