# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-14 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0089_auto_20181214_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='candidate_held_office',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='candidate_is_member',
            field=models.NullBooleanField(),
        ),
    ]
