# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0090_auto_20181214_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='candidate_held_office',
            field=models.NullBooleanField(verbose_name='Has the candidate ever held public office?'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='candidate_is_member',
            field=models.NullBooleanField(verbose_name='Is candidate a member of Our Revolution?'),
        ),
    ]
