# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-09 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0091_auto_20181214_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('needs-group-form-and-questionnaire', 'Needs Group Form and Questionnaire'), ('needs-questionnaire', 'Needs Questionnaire'), ('needs-group-form', 'Needs Group Form'), ('submitted', 'Submitted'), ('needs-research', 'Needs Research'), ('needs-staff-review', 'Needs Staff Review'), ('under-review', 'Under Review'), ('approved', 'Endorsed'), ('removed', 'Not Endorsed'), ('expired', 'Expired'), ('hold', 'Hold')], default='needs-group-form-and-questionnaire', max_length=64),
        ),
    ]
