# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-12 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0092_auto_20190109_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Basic Support'), (2, 'Priority Support')], null=True),
        ),
    ]
