# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:27
from __future__ import unicode_literals

from django.db import migrations


def create_base_pages(apps, schema_editor):
    from pages.models import BasePage, CandidateEndorsementIndexPage, IssueIndexPage, InitiativeEndorsementIndexPage
    from wagtail.wagtailcore.models import Page

    root = Page.objects.first()

    # Home Page
    base_page = BasePage(title='Our Revolution')
    root.add_child(instance=base_page)

    # Our Candidates
    candidate_endorsement_index = CandidateEndorsementIndexPage(title='Our Candidates', slug='candidates')
    base_page.add_child(instance=candidate_endorsement_index)

    # Our Initiatives
    initiative_endorsement_index = InitiativeEndorsementIndexPage(title='Our Initiatives', slug='ballot-initiatives')
    base_page.add_child(instance=initiative_endorsement_index)

    # Our Initiatives
    issue_index = IssueIndexPage(title='Our Issues', slug='issues')
    base_page.add_child(instance=issue_index)



def clear_base_pages(apps, schema_editor):
    from wagtail.wagtailcore.models import Page

    root = Page.objects.first()

    for page in root.get_children().all():
        page.delete()


def create_site(apps, schema_editor):
    from django.conf import settings
    from wagtail.wagtailcore.models import Site
    from pages.models import BasePage

    base_page = BasePage.objects.filter(title='Our Revolution').first()

    site_data = {
        'hostname': 'localhost' if settings.DEBUG else 'ourrevolution.com',
        'port': '8000' if settings.DEBUG else '80',
        'site_name': 'Our Revolution',
        'root_page': base_page,
        'is_default_site': True
    }

    site = Site.objects.create(**site_data)


def clear_site(apps, schema_editor):
    from wagtail.wagtailcore.models import Site

    Site.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_initiativeendorsementindexpage_initiativeendorsementpage_issueindexpage_issuepage'),
    ]

    operations = [
        migrations.RunPython(create_base_pages, reverse_code=clear_base_pages),
        migrations.RunPython(create_site, reverse_code=clear_site),
    ]
