# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 17:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_populate_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
