# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:20
from __future__ import unicode_literals

from django.db import migrations


def populate_news_index(apps, schema_editor):
    from pages.models import IndexPage, NewsIndex

    # Home Page
    home_page = IndexPage.objects.get(title='Our Revolution')


    # Our Candidates
    news_index = NewsIndex(title='News', slug='press')
    home_page.add_child(instance=news_index)


def remove_news_index(apps, schema_editor):
    from wagtail.wagtailcore.models import Page

    news_index = Page.objects.get(title='News')
    news_index.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20161024_1818'),
    ]

    operations = [
        migrations.RunPython(populate_news_index, reverse_code=remove_news_index)
    ]
