# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:10
from __future__ import unicode_literals

from django.db import migrations


def populate_take_action_page(apps, schema_editor):
    from pages.models import IndexPage, TemplatePage
    home_page = IndexPage.objects.get(title='Our Revolution')
    take_action_page = TemplatePage(title='Take Action', slug='action', template='pages/take_action.html')
    home_page.add_child(instance=take_action_page)


def remove_take_action_page(apps, schema_editor):
    from pages.models import TemplatePage
    TemplatePage.objects.get(title='Take Action').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_populate_about_page'),
    ]

    operations = [
        migrations.RunPython(populate_take_action_page, reverse_code=remove_take_action_page)
    ]
