# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 00:18
from __future__ import unicode_literals

from django.db import migrations


def populate_pages(apps, schema_editor):
    from pages.models import IndexPage, TemplatePage
    from wagtail.wagtailcore.models import Site
    from wagtail.wagtailredirects.models import Redirect

    bylaws = TemplatePage(title="Bylaws of Our Revolution", slug="bylaws", template="pages/bylaws.html")
    privacy = TemplatePage(title="Privacy Policy", slug="privacy-policy", template="pages/privacy_policy.html")

    home_page = IndexPage.objects.get(title='Our Revolution')
    home_page.add_child(instance=bylaws)
    home_page.add_child(instance=privacy)

    Redirect.objects.create(**{
        'old_path': '/page/bylaws',
        'site': Site.objects.get(is_default_site=True),
        'is_permanent': True,
        'redirect_page': bylaws
    })


def revert_pages(apps, schema_editor):
    from pages.models import IndexPage, TemplatePage
    from wagtail.wagtailcore.models import Site
    from wagtail.wagtailredirects.models import Redirect

    Redirect.objects.get(old_path='/page/bylaws').delete()

    TemplatePage.objects.get(title="Bylaws of Our Revolution").delete()
    TemplatePage.objects.get(title="Privacy Policy").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_create_redirects'),
    ]

    operations = [
        migrations.RunPython(populate_pages, reverse_code=revert_pages)
    ]
