# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('pages', '0017_odds_and_ends'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='templatepage',
        #     name='social_image',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        # ),
    ]
