# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_youtubepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubepage',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='youtubepage',
            name='youtube_video_id',
            field=models.CharField(default='Aq0ZsSK0_N8', max_length=20),
            preserve_default=False,
        ),
    ]
