# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 16:04
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_statesplashpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('rich_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock())], default=''),
            preserve_default=False,
        ),
    ]
