# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('pages', '0025_contentpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('abstract', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
