# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_donorlistpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorlistpage',
            old_name='csv',
            new_name='body',
        ),
    ]
