# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 23:48
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20170207_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorlistpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
