# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20170207_2348'),
        ('pages', '0026_donationpage'),
    ]

    operations = [
    ]
