# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_groupindexpage_grouppage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppage',
            name='body',
        ),
    ]
