# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('pages', '0032_remove_grouppage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='groupindexpage',
            name='social_image',
        ),
        migrations.RemoveField(
            model_name='grouppage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouppage',
            name='social_image',
        ),
        migrations.DeleteModel(
            name='GroupIndexPage',
        ),
    ]
