# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-10 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_peoplessummitstreampage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplessummitstreampage',
            name='livestream_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='peoplessummitstreampage',
            name='livestream_title',
            field=models.TextField(),
        ),
    ]
