# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_peoplessummitindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplessummitstreampage',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
