# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_peoplessummitstreampage_is_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplessummitstreampage',
            name='facebook_stream_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
