# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-01 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('link_text', models.CharField(max_length=128)),
                ('link_url', models.URLField()),
            ],
        ),
    ]
