# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_auto_20171107_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidaterace',
            name='margin_win_loss',
        ),
        migrations.AddField(
            model_name='candidaterace',
            name='show',
            field=models.BooleanField(default=False, help_text='Show the candidate race on the election results pages.'),
        ),
    ]
