# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-16 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_auto_20171107_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateendorsementindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementindexpage',
            name='content_heading',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
