# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_auto_20171107_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativerace',
            name='margin_win_loss',
        ),
    ]
