# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-20 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_micrositepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='accent_border_color',
            field=models.CharField(blank=True, help_text='6 digit CSS color code.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='micrositepage',
            name='show_accent_border',
            field=models.BooleanField(default=False, help_text='Show solid accent border at top of page.'),
        ),
    ]
