# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-20 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_auto_20171120_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositepage',
            name='custom_header_background_color',
            field=models.CharField(blank=True, help_text='6 digit CSS color code.', max_length=6, null=True),
        ),
    ]
