# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_candidaterace_election'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidaterace',
            name='election',
        ),
    ]
