# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0008_auto_20170118_1803'),
        ('pages', '0049_remove_candidaterace_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiontrackingpage',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endorsements.Election'),
        ),
    ]
