# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-06 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_groupresourcepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupresourcepage',
            name='sub_heading',
            field=models.TextField(blank=True, help_text='Optional text content to appear below page title.', null=True),
        ),
    ]
