# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-30 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_auto_20180129_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateendorsementpage',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Ignore - legacy field for old pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='endorsements.Candidate'),
        ),
    ]
