# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-30 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('pages', '0054_auto_20180130_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateendorsementpage',
            name='signup_tagline',
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='donate_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='general_election_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='general_election_result',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='office',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='primary_election_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='primary_election_result',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='state_or_territory',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='volunteer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateendorsementpage',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateendorsementpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='candidateendorsementpage',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Ignore - legacy field for old pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='endorsements.Candidate'),
        ),
    ]
