# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_auto_20180126_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='block_2_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='block_3_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='block_1_button_color',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='block_2_button_color',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='block_3_button_color',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red')], max_length=128, null=True),
        ),
    ]
