# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-05 22:21
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_membernewsletterpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernewsletterpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('white_background', wagtail.wagtailcore.blocks.RichTextBlock()), ('blue_background', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailcore.blocks.StructBlock([('photo', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('blue_background', wagtail.wagtailcore.blocks.RichTextBlock())]))]),
        ),
    ]
