# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-06 00:48
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_membernewsletterpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernewsletterpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('white_background', wagtail.wagtailcore.blocks.RichTextBlock()), ('blue_background', wagtail.wagtailcore.blocks.RichTextBlock()), ('image_block', wagtail.wagtailcore.blocks.StructBlock([('header', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False))]))]),
        ),
    ]
