# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-22 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_membernewsletterindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterace',
            name='candidate_endorsement_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.CandidateEndorsementPage'),
        ),
    ]
