# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-06 20:31
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_auto_20180206_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernewsletterpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('white_background', wagtail.wagtailcore.blocks.RichTextBlock()), ('blue_background', wagtail.wagtailcore.blocks.RichTextBlock()), ('image_block', wagtail.wagtailcore.blocks.StructBlock([('header', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock())]),
        ),
    ]
