# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-21 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_auto_20180222_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeendorsementpage',
            name='category',
            field=models.CharField(blank=True, choices=[('corporate-tax', 'Corporate Tax'), ('death-penalty', 'Death Penalty'), ('education', 'Education'), ('election-reform', 'Election Reform'), ('environment', 'Environment'), ('health-care', 'Health Care'), ('labor', 'Labor'), ('marijuana', 'Marijuana'), ('minimum-wage', 'Minimum Wage'), ('money-in-politics', 'Money in Politics')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='initiativeendorsementpage',
            name='election_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiativeendorsementpage',
            name='election_result',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='initiativeendorsementpage',
            name='how_to_vote',
            field=models.BooleanField(default=True, help_text='Check box for Vote Yes, uncheck for Vote No.', verbose_name='Vote Yes?'),
        ),
        migrations.AddField(
            model_name='initiativeendorsementpage',
            name='initiative_name',
            field=models.CharField(blank=True, help_text='Secondary name/subtitle of initiative.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='initiativeendorsementpage',
            name='initiative_title',
            field=models.CharField(blank=True, help_text='Primary title of initiative.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='initiativeendorsementpage',
            name='state_or_territory',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='initiativeendorsementpage',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiativeendorsementpage',
            name='initiative',
            field=models.ForeignKey(blank=True, help_text='Ignore - legacy field for old pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='endorsements.Initiative'),
        ),
        migrations.AlterField(
            model_name='initiativeendorsementpage',
            name='signup_tagline',
            field=models.CharField(blank=True, help_text='Ignore - legacy field for old pages.', max_length=128, null=True),
        ),
    ]
