# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_auto_20180321_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeendorsementpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check box to feature initiative at top of list.'),
        ),
    ]
