# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0061_initiativeendorsementpage_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='display_date_time',
            field=models.DateTimeField(null=True, verbose_name='Date & Time for display'),
        ),
    ]
