# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-28 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0062_newspost_display_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='display_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date & Time for display'),
        ),
    ]
