# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-26 16:11
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0064_auto_20180425_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernewsletterpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('white_block', wagtail.wagtailcore.blocks.RichTextBlock()), ('blue_block', wagtail.wagtailcore.blocks.RichTextBlock()), ('button_block', wagtail.wagtailcore.blocks.StructBlock([('content', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('button_copy', wagtail.wagtailcore.blocks.CharBlock(max_length=16, required=True)), ('button_url', wagtail.wagtailcore.blocks.URLBlock(required=True)), ('button_color', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red')], max_length=16, required=False))])), ('image_block', wagtail.wagtailcore.blocks.StructBlock([('header', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False))])), ('table_block', wagtail.wagtailcore.blocks.StructBlock([('header', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False))]))]),
        ),
    ]
