# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-18 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0064_auto_20180418_0051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberNewsletterIndexPage',
            new_name='EmailContentIndexPage',
        ),
        migrations.RenameModel(
            old_name='MemberNewsletterPage',
            new_name='EmailContentPage',
        ),
    ]
