# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-21 20:53
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0065_auto_20180426_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='board_list',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='staff_list',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
