# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-27 18:09
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0066_donationpage_csv_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpage',
            name='csv_files',
            field=wagtail.wagtailcore.fields.StreamField([('csv_file', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('quarter', wagtail.wagtailcore.blocks.CharBlock(max_length=16)), ('year', wagtail.wagtailcore.blocks.CharBlock(max_length=4))]),
        ),
    ]
