# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-03 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0066_auto_20180521_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeendorsementpage',
            name='how_to_vote',
            field=models.BooleanField(default=True, help_text='Ignore - legacy field for old pages.', verbose_name='Vote Yes?'),
        ),
        migrations.AlterField(
            model_name='initiativeendorsementpage',
            name='initiative_name',
            field=models.CharField(blank=True, help_text='Ignore - legacy field for old pages.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='initiativeendorsementpage',
            name='initiative_title',
            field=models.CharField(blank=True, help_text='Ignore - legacy field for old pages.', max_length=128, null=True),
        ),
    ]
