# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-02 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0066_auto_20180521_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateendorsementindexpage',
            name='button_show',
            field=models.BooleanField(default=True, help_text='Show nominations platform Get Started button.'),
        ),
        migrations.AddField(
            model_name='candidateendorsementindexpage',
            name='secondary_copy',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Copy to go below Past Election Results section.', null=True),
        ),
    ]
