# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-04 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0069_auto_20181002_2332'),
        ('pages', '0067_auto_20181003_2317'),
    ]

    operations = [
    ]
