# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-27 18:29
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0069_auto_20180427_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpage',
            name='csv_files',
            field=wagtail.wagtailcore.fields.StreamField([('donor_list', wagtail.wagtailcore.blocks.StructBlock([('csv_file', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('quarter', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], required=False)), ('year', wagtail.wagtailcore.blocks.CharBlock(max_length=4))]))]),
        ),
    ]
