# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-02 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0070_merge_20181004_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplashModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=False, help_text='Show splash modal on all pages.')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
    ]
