# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-27 18:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0070_auto_20180427_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationpage',
            name='csv_files',
        ),
        migrations.AddField(
            model_name='donationpage',
            name='donors',
            field=wagtail.wagtailcore.fields.StreamField([('donors_info', wagtail.wagtailcore.blocks.StructBlock([('csv_file', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('quarter', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], required=False)), ('year', wagtail.wagtailcore.blocks.CharBlock(max_length=4))]))], default=''),
            preserve_default=False,
        ),
    ]
