# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('pages', '0071_splashmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='splashmodal',
            name='background_color',
            field=models.CharField(blank=True, help_text='6 digit CSS color code.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='splashmodal',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='splashmodal',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splashmodal',
            name='donate_button_text',
            field=models.CharField(blank=True, help_text='Defaults to "Donate" if field is empty.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='splashmodal',
            name='donate_url',
            field=models.URLField(blank=True, help_text='Defaults to https://secure.actblue.com/contribute/page/ourrevolution if field is empty.', null=True),
        ),
        migrations.AlterField(
            model_name='splashmodal',
            name='title',
            field=models.CharField(help_text='Internal title for CMS use. Not public.', max_length=128),
        ),
    ]
