# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-06 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0072_auto_20181105_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='splashmodal',
            name='donate_recurring',
            field=models.BooleanField(default=False, help_text='Make recurring donation the default.'),
        ),
    ]
