# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-06 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0073_splashmodal_donate_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splashmodal',
            name='donate_url',
            field=models.URLField(blank=True, help_text='https://secure.actblue.com/contribute/page/ourrevolution is the default if field is empty.', null=True),
        ),
    ]
