# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-21 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0074_auto_20181106_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppage',
            name='featured_groups_show',
            field=models.BooleanField(default=False, help_text='Show Featured Groups list.'),
        ),
    ]
