# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsdprofile',
            name='cons_id',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
