# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsd', '0003_bsdevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=16)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
