# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('bsd', '0004_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('geo_json', models.TextField()),
                ('result', models.TextField(blank=True, null=True)),
                ('state_or_territory', localflavor.us.models.USStateField(max_length=2)),
                ('status', models.IntegerField(choices=[(1, 'New'), (10, 'In Progress'), (20, 'Complete')], default=1)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
    ]
