# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsd', '0005_geotarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotarget',
            name='result_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='geotarget',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (10, 'In Progress'), (20, 'Complete'), (30, 'No Results')], default=1),
        ),
    ]
