# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsd', '0008_auto_20181003_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geotarget',
            old_name='primary_addresses_only',
            new_name='primary_address_only',
        ),
    ]
