# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-04 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsd', '0010_auto_20181004_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotarget',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (10, 'In Progress'), (20, 'Complete'), (30, 'No Results')], default=1),
        ),
    ]
