# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='rep_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
    ]
