# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0003_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='social_media',
            new_name='other_social',
        ),
        migrations.AddField(
            model_name='group',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='meetup_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='recurring_meeting',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
