# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0004_auto_20170227_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='rep_phone',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
