# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 19:44
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0006_auto_20170301_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='types_of_organizing',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('direct-action', 'Direct Action'), ('electoral', 'Electoral Organizing'), ('legistlative', 'Advocating for Legislation or Ballot Measures'), ('community', 'Community Organizing'), ('other', 'Other')], max_length=52, null=True),
        ),
    ]
