# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0007_auto_20170301_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='other_types_of_organizing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
