# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import endorsements.models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0008_auto_20170118_1803'),
        ('local_groups', '0008_group_other_types_of_organizing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='issues',
        ),
        migrations.AddField(
            model_name='group',
            name='issues',
            field=models.ManyToManyField(to='endorsements.Issue'),
        ),
        migrations.AlterField(
            model_name='group',
            name='other_types_of_organizing',
            field=models.TextField(default='', verbose_name=endorsements.models.Issue),
            preserve_default=False,
        ),
    ]
