# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 18:07
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0011_auto_20170301_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
