# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0012_group_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
