# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0013_group_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='rep_zip_code',
        ),
        migrations.AddField(
            model_name='group',
            name='rep_postal_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
