# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 19:40
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0015_group_other_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='recurring_meeting',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
