# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 23:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0017_group_recurring_meeting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
