# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0018_group_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('signed-mou', 'Signed MOU'), ('approved', 'Approved'), ('removed', 'Removed')], default='submitted', max_length=16),
        ),
    ]
