# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0019_group_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='leadership_positions',
        ),
        migrations.RemoveField(
            model_name='group',
            name='leadership_structure',
        ),
    ]
