# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0024_auto_20170307_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='group',
            name='longitude',
        ),
    ]
