# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 03:28
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0025_auto_20170307_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='meetup_url',
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Description (250 characters or less)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='group',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_meeting',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Meeting'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='other_issues',
            field=models.TextField(blank=True, null=True, verbose_name='Other Issues'),
        ),
        migrations.AlterField(
            model_name='group',
            name='other_social',
            field=models.TextField(blank=True, null=True, verbose_name='Other Social Media'),
        ),
        migrations.AlterField(
            model_name='group',
            name='other_types_of_organizing',
            field=models.TextField(blank=True, null=True, verbose_name='Other Types of Organizing'),
        ),
        migrations.AlterField(
            model_name='group',
            name='recurring_meeting',
            field=recurrence.fields.RecurrenceField(blank=True, null=True, verbose_name='Recurring Meeting'),
        ),
        migrations.AlterField(
            model_name='group',
            name='recurring_meeting_location',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='Recurring Meeting Address'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_first_name',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_last_name',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='group',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='group',
            name='types_of_organizing',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('direct-action', 'Direct Action'), ('electoral', 'Electoral Organizing'), ('legistlative', 'Advocating for Legislation or Ballot Measures'), ('community', 'Community Organizing'), ('other', 'Other')], max_length=52, null=True, verbose_name='Types of Organizing'),
        ),
        migrations.AlterField(
            model_name='group',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
    ]
