# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0026_auto_20170308_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='group',
            name='size',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='Group Size'),
        ),
    ]
