# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0027_auto_20170308_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=250, null=True, verbose_name='Description (250 characters or less)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='postal_code',
            field=models.CharField(max_length=12, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_first_name',
            field=models.CharField(blank=True, default='John', max_length=9, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_last_name',
            field=models.CharField(blank=True, default='Doe', max_length=12, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
