# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0028_auto_20170308_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='rep_first_name',
            field=models.CharField(max_length=9, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_last_name',
            field=models.CharField(max_length=12, null=True, verbose_name='Last Name'),
        ),
    ]
