# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 22:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0029_auto_20170308_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
