# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0030_auto_20170308_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='issues',
            field=models.ManyToManyField(blank=True, to='endorsements.Issue'),
        ),
    ]
