# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0033_auto_20170309_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='meeting_address_line1',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_address_line2',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='group',
            name='state_province',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='State/Province'),
        ),
    ]
