# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0036_auto_20170309_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='meeting_country',
            field=django_countries.fields.CountryField(blank=True, default='US', max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='group',
            name='recurring_meeting',
            field=recurrence.fields.RecurrenceField(blank=True, help_text='test', null=True, verbose_name='Recurring Meeting'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_first_name',
            field=models.CharField(max_length=64, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_last_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Last Name'),
        ),
    ]
