# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0037_auto_20170310_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
