# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0038_group_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='constituency',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='other_issues',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Other Issues'),
        ),
        migrations.AlterField(
            model_name='group',
            name='other_social',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Other Social Media'),
        ),
    ]
