# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0040_auto_20170313_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='rep_first_name',
            field=models.CharField(max_length=35, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='rep_last_name',
            field=models.CharField(max_length=35, null=True, verbose_name='Last Name'),
        ),
    ]
