# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0042_auto_20170313_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='county',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
