# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0043_auto_20170313_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='group',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='group',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='group',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website URL'),
        ),
    ]
