# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0044_auto_20170313_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
