# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 20:41
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0045_auto_20170313_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='recurring_meeting',
            field=recurrence.fields.RecurrenceField(blank=True, null=True, verbose_name='Recurring Meeting'),
        ),
    ]
