# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0046_auto_20170322_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code'),
        ),
    ]
