# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0048_group_state_organizing_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
