# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0049_auto_20170606_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Description (1000 characters or less)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='other_types_of_organizing',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Other Types of Organizing'),
        ),
    ]
