# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-19 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0049_auto_20170606_2331'),
        ('local_groups', '0049_auto_20170616_1917'),
    ]

    operations = [
    ]
