# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-29 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0052_auto_20170807_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='signed_mou_version',
            field=models.CharField(choices=[('none', 'N/A'), ('1.0', 'Old'), ('1.1', 'Current')], default='none', max_length=64, verbose_name='MOU Version'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('signed-mou', 'Signed MOU'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('removed', 'Removed')], default='submitted', max_length=64),
        ),
    ]
