# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-29 17:40
from __future__ import unicode_literals

from django.db import migrations, models


def set_signed_mou_version(apps, schema_editor):
    GroupsModel = apps.get_model('local_groups', 'Group')
    
    for group in GroupsModel.objects.all():
        if group.status == 'approved' or group.status == 'signed-mou' and group.signed_mou_version == 'none':
            print group
            group.signed_mou_version = '1.0'
            group.save()
            
def unset_signed_mou_version(apps, schema_editor):
    GroupsModel = apps.get_model('local_groups', 'Group')
    
    for group in GroupsModel.objects.all():
        if group.status == 'approved' or group.status == 'signed-mou' and group.signed_mou_version == '1.0':
            group.signed_mou_version = 'none'
            group.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0053_auto_20170829_1740'),
    ]

    operations = [
        migrations.RunPython(set_signed_mou_version, reverse_code=unset_signed_mou_version)
    ]
