# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-29 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0054_auto_20170829_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='signed_mou_version',
            field=models.CharField(blank=True, choices=[('none', 'N/A'), ('1.0', 'Old'), ('1.1', 'Current')], default='none', max_length=64, null=True, verbose_name='MOU Version'),
        ),
    ]
