# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0055_auto_20170829_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mou_url',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='MOU URL'),
        ),
        migrations.AddField(
            model_name='group',
            name='organizer',
            field=models.CharField(blank=True, choices=[('juliana', 'Juliana'), ('basi', 'Basi'), ('kyle', 'Kyle')], default=None, max_length=64, null=True, verbose_name='Organizer'),
        ),
    ]
