# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-28 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0057_auto_20170829_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notes',
            field=models.TextField(blank=True, help_text='Please include dates here along with notes to make\n                    reporting easier.', null=True, verbose_name='Notes'),
        ),
    ]
