# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-13 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0059_group_group_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_contact_email',
            field=models.EmailField(blank=True, help_text='Optional Group Contact Email to publicly display an email\n        different from Group Leader Email', max_length=254, null=True),
        ),
    ]
