# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-07 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0060_auto_20171213_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='state_organizing_committee',
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('state-organizing-committee', 'State Organizing Committee'), ('state-chapter', 'State Chapter'), ('campus', 'Campus'), ('local-group', 'Local Group')], default='local-group', max_length=64),
        ),
    ]
