# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-07 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0061_auto_20180207_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, choices=[('state-organizing-committee', 'State Organizing Committee'), ('state-chapter', 'State Chapter'), ('campus', 'Campus'), ('local-group', 'Local Group')], default='local-group', max_length=64, null=True),
        ),
    ]
