# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-07 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0061_group_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='state_organizing_committee',
        ),
    ]
