# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-08 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0062_remove_group_state_organizing_committee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0, help_text='Including guests. Leave 0 for unlimited.', verbose_name='Capacity Limit')),
                ('contact_phone', models.CharField(max_length=25)),
                ('creator_name', models.CharField(max_length=255, verbose_name='Host Name')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('host_receive_rsvp_emails', models.IntegerField(default=1, verbose_name='Notify me when new people RSVP')),
                ('public_phone', models.IntegerField(default=1, verbose_name='Make my phone number public to attendees')),
                ('start_day', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('start_tz', models.CharField(choices=[('US/Eastern', 'Eastern'), ('US/Central', 'Central'), ('US/Mountain', 'Mountain'), ('US/Pacific', 'Pacific'), ('US/Alaska', 'Alaska'), ('US/Hawaii', 'Hawaii')], default='America/Eastern', max_length=40, null=True, verbose_name='Time Zone')),
                ('venue_name', models.CharField(max_length=255, verbose_name='Venue Name')),
                ('venue_addr1', models.CharField(max_length=255, verbose_name='Venue Address')),
                ('venue_addr2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Venue Address #2')),
                ('venue_city', models.CharField(max_length=64, verbose_name='Venue City')),
                ('venue_country', models.CharField(default='US', max_length=2, verbose_name='Venue Country')),
                ('venue_directions', models.TextField(blank=True, null=True, verbose_name='Directions to Venue')),
                ('venue_state_cd', localflavor.us.models.USStateField(max_length=2, verbose_name='Venue State')),
                ('venue_zip', models.CharField(max_length=16, verbose_name='Venue Zip Code')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
