# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-30 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('local_groups', '0064_auto_20180525_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.IntegerField(choices=[(1, 'Group Leader'), (2, 'Group Admin')], unique=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission')),
            ],
        ),
        migrations.RemoveField(
            model_name='localgroupaffiliation',
            name='auth_groups',
        ),
        migrations.AddField(
            model_name='localgroupaffiliation',
            name='local_group_roles',
            field=models.ManyToManyField(blank=True, to='local_groups.LocalGroupRole'),
        ),
    ]
