# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-07 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0066_auto_20180530_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localgroupaffiliation',
            options={'ordering': ['local_group__name', 'local_group__group_id', 'local_group_profile__user__email']},
        ),
        migrations.AlterModelOptions(
            name='localgroupprofile',
            options={'ordering': ['user__email']},
        ),
    ]
