# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0067_auto_20180607_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Strongly aligned with values and expectations'), (4, 'Somewhat aligned with values and expectations'), (3, 'Working toward alignment values and expectations'), (2, 'Somewhat misaligned or resistant to values and expectations'), (1, 'Group inactive or very misaligned with values and expectations')], null=True),
        ),
    ]
