# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_groups', '0069_auto_20180806_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_rating',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Strongly aligned with values and expectations'), (4, '4 - Somewhat aligned with values and expectations'), (3, '3 - Working toward alignment with values and expectations'), (2, '2 - Somewhat misaligned or resistant to values and expectations'), (1, '1 - Group inactive or very misaligned with values and expectations')], null=True),
        ),
    ]
