# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-17 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('transform', '0002_transformpartypage_social_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformpartyindexpage',
            name='primary_content',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformpartyindexpage',
            name='primary_content_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='transformpartyindexpage',
            name='secondary_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformpartyindexpage',
            name='signup_embed_code',
            field=models.TextField(blank=True, help_text='Raw HTML embed code for signup form, etc.', null=True),
        ),
        migrations.AddField(
            model_name='transformpartyindexpage',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
