# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('office', models.CharField(blank=True, max_length=128, null=True)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('state_initials', models.CharField(blank=True, max_length=32, null=True)),
                ('primary_date', models.DateField(blank=True, null=True)),
                ('primary_results', models.URLField(blank=True, null=True)),
                ('won_primary', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('show', models.BooleanField(default=False)),
                ('primary_cta', models.CharField(blank=True, max_length=32, null=True)),
                ('primary_cta_enabled', models.BooleanField(default=False)),
                ('primary_cta_link', models.URLField(blank=True, null=True)),
                ('secondary_cta', models.CharField(blank=True, max_length=32, null=True)),
                ('secondary_cta_link', models.URLField(blank=True, null=True)),
                ('polling_locator', models.URLField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('header_photo', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
