# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 23:48
from __future__ import unicode_literals
from datetime import datetime
from django.db import migrations
import requests


def populate_candidate_endorsements(apps, schema_editor):
    Candidate = apps.get_model('endorsements', 'Candidate')

    source = "https://raw.githubusercontent.com/Our-Revolution/launch-site/master/data/candidates.json"
    candidates = requests.get(source).json()

    TRUEs_and_FALSEs = ['show', 'won_primary', 'primary_cta_enabled', 'featured']
    Yes_and_Nos = ['approved']

    for key, candidate_data in candidates.iteritems():

        for prop in TRUEs_and_FALSEs:
            if prop in candidate_data:
                if candidate_data[prop] == 'TRUE':
                    candidate_data[prop] = True
                else: # elif prop in candidate_data and candidate_data[prop] == 'FALSE':
                    candidate_data[prop] = False
        
        for prop in Yes_and_Nos:
            if prop in candidate_data:
                if candidate_data[prop] == 'Yes':
                    candidate_data[prop] = True
                else: # elif candidate_data[prop] == 'No':
                    candidate_data[prop] = False

        if 'primary_date' in candidate_data and candidate_data['primary_date']:
            candidate_data['primary_date'] = datetime.strptime(candidate_data['primary_date'], "%m/%d/%Y")
        else:
            candidate_data['primary_date'] = None

        candidate = Candidate.objects.create(**candidate_data)


def truncate_candidate_endorsements(apps, schema_editor):
    Candidate = apps.get_model('endorsements', 'Candidate')
    Candidate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_candidate_endorsements, reverse_code=truncate_candidate_endorsements)
    ]
