# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0002_populate_candidate_endorsements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vote', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('state_initials', models.CharField(blank=True, max_length=32, null=True)),
                ('show', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('cta', models.CharField(blank=True, max_length=32, null=True)),
                ('cta_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
