# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 00:19
from __future__ import unicode_literals
from django.db import migrations
import requests


def populate_initiative_endorsements(apps, schema_editor):
    Initiative = apps.get_model('endorsements', 'Initiative')

    source = "https://raw.githubusercontent.com/Our-Revolution/launch-site/master/data/initiatives.json"
    initiatives = requests.get(source).json()

    TRUEs_and_FALSEs = ['show', 'featured']
    Yes_and_Nos = ['vote']

    for key, initiative_data in initiatives.iteritems():

        for prop in TRUEs_and_FALSEs:
            if prop in initiative_data:
                if initiative_data[prop] == 'TRUE':
                    initiative_data[prop] = True
                else: # elif prop in initiative_data and initiative_data[prop] == 'FALSE':
                    initiative_data[prop] = False
        
        for prop in Yes_and_Nos:
            if prop in initiative_data:
                if initiative_data[prop] == 'Yes':
                    initiative_data[prop] = True
                else: # elif initiative_data[prop] == 'No':
                    initiative_data[prop] = False

        initiative = Initiative.objects.create(**initiative_data)


def truncate_initiative_endorsements(apps, schema_editor):
    Initiative = apps.get_model('endorsements', 'Initiative')
    Initiative.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0003_initiative'),
    ]

    operations = [
        migrations.RunPython(populate_initiative_endorsements, reverse_code=truncate_initiative_endorsements)
    ]
