# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 22:11
from __future__ import unicode_literals
from django.db import migrations
import requests


def populate_issues(apps, schema_editor):
    Issue = apps.get_model('endorsements', 'Issue')

    source = "https://raw.githubusercontent.com/Our-Revolution/launch-site/master/data/issues.json"
    issues = requests.get(source).json()

    for issue_data in issues:
        issue = Issue.objects.create(**issue_data)


def truncate_issues(apps, schema_editor):
    Issue = apps.get_model('endorsements', 'Issue')
    Issue.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0005_issue'),
    ]

    operations = [
        migrations.RunPython(populate_issues, reverse_code=truncate_issues)
    ]
