# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:22
from __future__ import unicode_literals

from django.core.files.images import ImageFile
from django.core.files import File
from django.db import migrations, models
from io import BytesIO

import requests


def populate_candidate_images(apps, schema_editor):
    from endorsements.models import Candidate


    for candidate in Candidate.objects.all():
        req = requests.get('https://our-revolution-dot-com.s3.amazonaws.com/%s.jpg' % candidate.slug)
        photo = ImageFile(BytesIO(req.content))
        candidate.photo.save(candidate.slug + '.jpg', photo, save=True)
        # candidate.save()

        print "saved %s" % candidate


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0008_auto_20170118_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='header_photo',
            new_name='header_photo_source',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='photo',
            new_name='photo_source',
        ),
        migrations.AddField(
            model_name='candidate',
            name='header_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.RunPython(populate_candidate_images, reverse_code=migrations.RunPython.noop)
    ]
