# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-16 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0008_auto_20170118_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-id']},
        ),
    ]
