# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-29 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0009_auto_20180116_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_active',
        ),
    ]
