# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0039_collectionviewrestriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('primary_content_background_color', models.CharField(blank=True, help_text='6 digit CSS color code.', max_length=6, null=True)),
                ('primary_content_body', wagtail.wagtailcore.fields.RichTextField()),
                ('primary_content_button_text', models.CharField(max_length=128)),
                ('primary_content_embed_code', models.TextField(help_text='Raw HTML embed code for signup form, etc.')),
                ('primary_content_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
