# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 21:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_pages', '0002_auto_20180810_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaypage',
            name='section_3_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
