# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('birthday_pages', '0003_birthdaypage_section_3_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdaypage',
            old_name='section_2_1_background_image',
            new_name='section_2_1_image',
        ),
        migrations.RenameField(
            model_name='birthdaypage',
            old_name='section_2_2_background_image',
            new_name='section_2_2_image',
        ),
        migrations.RenameField(
            model_name='birthdaypage',
            old_name='section_2_3_background_image',
            new_name='section_2_3_image',
        ),
        migrations.RenameField(
            model_name='birthdaypage',
            old_name='section_2_4_background_image',
            new_name='section_2_4_image',
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_1_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_1_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_2_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_2_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_3_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_3_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_4_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_4_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_5_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_5_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_6_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_6_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_7_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_7_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_8_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_8_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthdaypage',
            name='section_2_1_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthdaypage',
            name='section_2_2_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthdaypage',
            name='section_2_3_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthdaypage',
            name='section_2_4_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
