# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('birthday_pages', '0004_auto_20180813_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaypage',
            name='section_4_background_color',
            field=models.CharField(blank=True, help_text='6 digit CSS color code.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_5_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_5_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_6_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_6_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_7_background_color',
            field=models.CharField(blank=True, help_text='6 digit CSS color code.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_7_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_7_body',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_7_button_new_window',
            field=models.BooleanField(default=False, help_text='Open link in new window?'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_7_button_text',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='section_7_button_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
