# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_pages', '0006_auto_20180815_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaypage',
            name='header_button_new_window',
            field=models.BooleanField(default=False, help_text='Open link in new window?'),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='header_button_text',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='header_button_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='progress_bar_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='progress_bar_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='progress_bar_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='progress_bar_goal_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='progress_bar_goal_new',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
