# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_pages', '0008_birthdaypage_header_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdaypage',
            old_name='header_background_image',
            new_name='header_border_image',
        ),
        migrations.AddField(
            model_name='birthdaypage',
            name='header_border_color',
            field=models.CharField(blank=True, help_text='6 digit CSS color code.', max_length=6, null=True),
        ),
    ]
