# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_pages', '0009_auto_20180817_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaypage',
            name='primary_content_embed_layout',
            field=models.IntegerField(choices=[(1, '16x9'), (2, '4x3'), (3, 'Square')], default=1),
        ),
    ]
