# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('social_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('old_path', models.CharField(db_index=True, help_text=b"This should be an absolute path, excluding the domain name. Example: '/events/search/'.", max_length=200, verbose_name=b'Redirect From')),
                ('new_path', models.CharField(blank=True, help_text=b"This can be either an absolute path (as above) or a full URL starting with 'http://'.", max_length=200, verbose_name=b'Redirect To')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('old_path',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='redirect',
            unique_together=set([('site', 'old_path')]),
        ),
    ]
